# General Settings
name: Steven Harman
title: Steven Harman
job_title: Maker & Breaker of Things
email: steven@harmanly.com
description: Designer and developer of software. Believes the pursuit of beauty yields simplicity. Creator and consumer of open source software. Good at naps!
title_image: /assets/images/steven-avatar.jpg
# avatar: https://example.com/hi.png
favicon: /favicon.ico
twitter_handler: stevenharman
analytics_code: YFDWOMYW
disqus: stevenharman
github_username: stevenharman

# Social Accounts
social_networks:
- { name: facebook, url: '' }
- { name: twitter, url: 'https://twitter.com/stevenharman' }
- { name: instagram, url: '' }
- { name: google-plus, url: '' }
- { name: linkedin, url: '' }
- { name: skype, url: '' }
- { name: github, url: 'https://github.com/stevenharman' }
- { name: codepen, url: '' }
- { name: stack-overflow, url: 'https://stackoverflow.com/users/18152/stevenharman' }
- { name: dribbble, url: '' }
- { name: behance, url: '' }
- { name: pinterest, url: '' }
- { name: tumblr, url: '' }
- { name: youtube, url: '' }
- { name: vimeo, url: '' }
- { name: vine, url: '' }
- { name: 500px, url: '' }
- { name: flickr, url: '' }
- { name: spotify, url: '' }
- { name: steam, url: '' }
- { name: wordpress, url: '' }
- { name: xing, url: '' }
- { name: bitcoin, url: '' }
- { name: pocket, url: '' }
- { name: applemusic, url: 'https://itunes.apple.com/profile/stevenharman' }
- { name: mastodon, url: 'https://ruby.social/@stevenharman' }

# Modules Settings
show_categories: 0
show_tags: 0
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://stevenharman.net"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: ":slug"
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!-- more -->"

# Assets Settings
sass:
  sass_dir: assets/css
  style: compressed
